### ISSUE TITLE
Zepto-Based version

### ISSUE THREAD

**Issue by leo-unglaub** [masasron/iosCheckbox.js#1]
Hi,
thanks for the Plugin. It works great. I took the liberty to rewrite it to use Zepto instead of jQuery. The Version is hosted here: https://bitbucket.org/foxship/ioscheckbox.js

Maybe this helps someone who also needs a Zepto-Version of your plugin. Maybe you could add a link in your Readme file to the Zepto version.

Greetings
Leo

**Comment by masasron** [comment]
Hi,
Sorry about the delay, thank you for doing this.
added to the Readme file.
