### ISSUE TITLE
Not resetting after another call

### ISSUE THREAD

**Issue by zoranlorkovic** [masasron/iosCheckbox.js#2]
This is cool plugin, however there is problem is you need to call checkbox plugin when calling modal box.
Then, every time you call plugin, it creates new checkboxes, not resetting it and then creating.

**Comment by masasron** [comment]
Hi @zlorkovic thanks for the bug report.
Bug was solved. :+1: 

http://jsfiddle.net/3jtrn6ec/

**Comment by zoranlorkovic** [comment]
Hi @masasron 

This solution works, but there is problem if checkbox state changes between calls.

For example. I'm opening one form in modal box which is for displaying user data. User can be active or inactive. When I open modal box, I setup checkbox to checked or not checked, based on user data.
With your solution, checkbox will have same state for every call (based on user data for first call), no matter did I changed state of checkbox.

Solution which worked for me is to destroy created iOS checkbox and recreate it again.

Something like:
`
                /**
                 * Remove previous checkboxes
                 */
                org_checkbox.next('.ios-ui-select').remove();
`

**Comment by masasron** [comment]
Added a `destroy` function.

``` js
var c = $(".ios").iosCheckbox();
$("button").click(function (){
     c.destroy();
});
```

http://jsfiddle.net/bttkc3jg/17/
